module.exports = {
  docs: {
    "Getting Started": [
      "getting-started/getting-started",
      "getting-started/typescript-support",
      "getting-started/integration-an-existing-form",
      "getting-started/validation-guide",
      "getting-started/form-submission",
      "getting-started/reset-form",
      "getting-started/form-state",
      "getting-started/complex-structures",
      "getting-started/3rd-party-ui-libraries",
    ],
    Examples: [
      "examples/basic",
      "examples/built-in-validation",
      "examples/form-level-validation",
      "examples/field-level-validation",
      "examples/validation-with-yup",
      "examples/validation-with-joi",
      "examples/form-submission",
      "examples/reset-form",
      "examples/checkboxes",
      "examples/radio-group",
      "examples/multi-select",
      "examples/complex-structures",
      "examples/conditional-fields",
      "examples/lazy-default-values",
      "examples/material-ui",
      "examples/react-select",
    ],
    "API Reference": [
      "api-reference/use-form",
      "api-reference/utility-functions",
    ],
  },
};
